export const CREATE_SURVEY = "CREATE_SURVEY";
export const FETCH_SURVEYS = "FETCH_SURVEYS";
export const FETCH_SURVEY = "FETCH_SURVEY";
export const DELETE_SURVEY = "DELETE_SURVEY";
export const EDIT_SURVEY = "EDIT_SURVEY";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
